### ISSUE TITLE
use_frameworks! And Error

### ISSUE THREAD

**Issue by MartinWong-H** [MyScript/interactive-ink-examples-ios#2]
hello, I hava a problem while use the MyScript , 
if I  pod this MyScript  with use_frameworks! that get a error
could not build Objective-C module 'MyScriptInteractiveInk_Runtime'

but if i get rid of use_frameworks!  my project will have many errors from Third party library
how can i do this ?

**Comment by MyScriptSupport** [comment]
Dear Martin,
as  you can see in the following blog post, developers are no longer  restricted into specifying use_frameworks in their Podfile in order to  install pods that use Swift: http://blog.cocoapods.org/CocoaPods-1.5.0/
In order to no longer have the error, you should then remove it.

Best regards,
Olivier

**Comment by fankcool** [comment]
hi, I get a exception, libc++abi.dylib: terminating with uncaught exception of type myscript::engine::EngineError: INDEX_OUT_OF_BOUNDS, what should i do ?

**Comment by MyScriptSupport** [comment]
Dear FankFank,

thank you for contacting us.
Currently, would you have a stack frame? Which function are you calling when the exception occurs?
If when calling the "getPart" function, this would be likely because the index part you are providing is higher than the number of parts: https://developer.myscript.com/refguides/interactive-ink/android/1.3/com/myscript/iink/ContentPackage.html#getPart-int-

Best regards,
Olivier

**Comment by fankfank** [comment]
thanks a lot, the exception occurs when create a lot of images through the engine, hundreds of pictures.

**Comment by fankcool** [comment]
thanks a lot , the exception occurs when create a lot of images through the engine, hundreds of pictures.

**Comment by fankfank** [comment]
My company is a paid user. I have not found such a mistake on the forum. What can I do?

**Comment by thearshadali** [comment]
Hi,Could you tell me how to use your framework in swift based project Please.Your documentation is not clear.

**Comment by thearshadali** [comment]
pod "MyScriptInteractiveInk-UIReferenceImplementation"
Is not working.

**Comment by ponpoko1968** [comment]
@thearshadali 
try:
`pod 'MyScriptInteractiveInk-UIReferenceImplementation', :git => 'git@github.com:MyScript/interactive-ink-examples-ios.git'`
works  my envionment.
